name: reserva_churas
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  dio: ^5.1.1
  provider: ^6.0.5
  loading_gifs: ^0.3.0
  loading_animation_widget: ^1.2.0+4
  top_snackbar_flutter: ^3.0.0+1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  match: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  match_generator: ^0.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
